### ISSUE TITLE
.Decode() indexing panic

### ISSUE THREAD

**Issue by samhithatarra** [CrowdStrike/csproto#158]
## Title

.Decode() method panics instead of error
## Version

v0.30.0
## Description

In some cases the .Decode() method which calls Skip() method here -> https://github.com/CrowdStrike/csproto/blob/main/decoder.go#L903, panics if indexing is out of range. Can we add a check here to fail/error rather than panic

**Comment by dylan-bourque** [comment]
Looks like this panic is happening due to an invalid/corrupt message where the length of a string/bytes field is > `math.MaxInt64`, which causes the value to be negative when converted from `uint64` to `int`.  `d.offset += skipped` line at the end of `Skip()` to store a negative offset and the `return d.p[bof:d.offset], nil` line below to panic.
